### ISSUE TITLE
笠間焼の体験をしてみる

### ISSUE THREAD

**Issue by dimbula** [waprojecthq/WA#101]
■笠間焼の体験をしてみる
・笠間 工芸の丘
http://www.kasama-crafthills.co.jp/tougei/
・

_Originally posted by @ojimashun in https://github.com/waprojecthq/WA/issues/67#issuecomment-1103318437_

**Comment by ojimashun** [comment]
【桧佐陶工房】
https://kasama-hisa.jp/
・登り窯もある
・作りたいものの相談もできるみたい。まずはここで相談をしてみたいかも
