### ISSUE TITLE
アライさんにアルバリーニョを植えたいという相談をする

### ISSUE THREAD

**Issue by dimbula** [waprojecthq/WA#225]

**Comment by typeriver** [comment]
電話にて相談。

新井さんのところは、Tettaから休眠枝をもらって自根で挿木。
新井さんのところの緑枝は耐えられるような感じじゃない。

アイデアとして、アルバリーニョを植えている、以下のようなワイナリーさんに連絡してみることで、苗木を分けてもらえる　or. りょくしをもらえる、苗木やさんを紹介してもらえるとか道が開けるかもというアイデアをいただきました。

・カーブ・ドッチ
・セイズ・ファーム
・Tetta
