### ISSUE TITLE
「自然にやさしい」トーク

### ISSUE THREAD

**Issue by typeriver** [waprojecthq/WA#246]

**Comment by dimbula** [comment]
https://docs.google.com/document/d/17hsCB8-_ZhoncF1hNMplT73pJNvH-o5N5uTaBjN7XhE/edit#heading=h.zhuiuco8nnf4

**Comment by dimbula** [comment]
@typeriver 
反応見てちょっとアプローチが違うのかなと思ったので、100本ノックは一旦ナシでお願いします！
